version = 1

test_patterns = [
  "test/**",
  "tests/tests_*.py",
  "**/*_test.py"
]

exclude_patterns = [
  "migrations/**",
  "tests/project/**"
]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"