# Generated by Django 4.1.5 on 2023-01-14 05:40

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', post.models.ValidatedFileField(upload_to='')),
                ('name', models.TextField()),
                ('reza', models.CharField(max_length=1212)),
            ],
        ),
    ]
