# Generated by Django 4.1 on 2022-08-11 22:27

from django.db import migrations, models
import file_validator.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='', validators=[file_validator.django.FileValidatorByMimeTypes('image/png', 'video/mp4')])),
            ],
        ),
    ]
