name: Workflow for Codecov 
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -r requirements_dev.txt
      - name: install python-magic
        run: sudo pip install python-magic
      - name: Run tests and collect coverage
        run: pytest --cov file_validator
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
