name: CI
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@v1.2
        with:
          source-folder: docs
          git-user: file-validator
          git-password: ${{ secrets.MY_GITHUB_TOKEN }}
          deployment-branch: master
