 
name: Docker build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
  
    steps:
     - uses: actions/checkout@v2
     - name: Build Docker image 
       run: docker build -t samplepy .
     - name: Run tests inside the container
       run: docker run samplepy poetry run pytest
