name: Test with docker

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "/home/runner/work/file-validator/file-validator/docker-compose.yml"
